baseURL = "https://bun4.com/"
languageCode = "en-us"
title = "Bun4 - Grow Your Inner Dev"
theme = "vanilla-bootstrap-hugo-theme"


[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    pre = "smile"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    pre = "rss"
    url = "/index.xml"
    weight = 4

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
